plugins {
    id("java")
    id('org.jetbrains.intellij') version '1.10.1'
}

group 'io.github.newhoo.restkit.ext'
version '1.0.4'

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'
//    compileOnly fileTree(dir: 'libs', includes: ['*jar'])
}

intellij {
    pluginName.set('RestfulBox-Solon')
    version.set('2024.1')
//    type.set("IU")
    updateSinceUntilBuild.set(false)
    downloadSources.set(true)
//    plugins.set(['java', 'io.github.newhoo.restkit:4.0.0'])
    plugins.set(['java', file("D:/Projects/Plugins/RestfulBox-Plus/build/libs/RestfulBox-5.3.0-obfuscated.jar")])
    sandboxDir.set("${rootProject.rootDir}/idea-sandbox")
}

tasks {

//    verifyPluginConfiguration {
//        enabled = false
//    }

    buildSearchableOptions {
        enabled = false
    }
}